---
- name: Remove user and home directory
  hosts: all
  become: yes
  tasks:
    - name: Ensure the user 'aryan' is absent
      user:
        name: aryan
        state: absent

    - name: Remove home directory of user 'aryan'
      file:
        path: /home/user/aryan
        state: absent

